### ISSUE TITLE
Would you help me?

### ISSUE THREAD

**Issue by mardonedias** [toniher/docker-couchdb-lucene#2]
Good evening,

I've been trying for some time to configure lucene with couchdb with this image of yours.

I don't understand how the integration works, but after a lot of searching I managed to set up an environment with his image.

But, I'm not sure it's working. Lucene is opening, but I can't do any tests. leaving me in doubt if the integration is really working.

**VIEW**

```
function (doc) {
  if (doc.$typedoc === 'module') {
    emit(doc.nome.toLowerCase() + " - " + doc.descricao, null);
  }
}
```

**INDEXES**
```
{
  "_id": "_design/modules",
  "fulltext": {
    "by_nome": {
      "index": "function(doc) { var ret=new Document(); ret.add(doc.nome, { field: 'nome', store: 'yes'}); return ret }"
    }
  }
}
```

**lucene-proxy.ini**

```
[httpd_global_handlers]
_fti = {couch_httpd_proxy, handle_proxy_req, <<"http://couchdb-lucene:5985">>}
```

**DOCKER COMPOSE**
```
couchdb:
    container_name: couchdb-dev
    image: couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - '5984:5984'
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./.docker/dev/couchdb/lucene-proxy.ini:/opt/couchdb/etc/local.d/lucene-proxy.ini
    networks:
      - interna
      - externa

couchdb-lucene:
    container_name: couchdb-lucene-dev
    image: toniher/couchdb-lucene:2.1.0
    restart: always
    environment: 
      - COUCHDB_PORT=5984
      - COUCHDB_SERVER=couchdb
    ports:
      - '5985:5985'
    volumes:
      - ./.docker/dev/couchdb/indexes/:/opt/couchdb-lucene/indexes/
    links:
      - couchdb
    networks:
      - interna
      - externa
```
